----
 - 官网文档：``http://docs.pytest.org/en/latest/``
 - 版本：pytest-3.0.7
 - 译者：怪兽穿拖鞋（TavisD）
 - 邮箱：tavisdxh@outlook.com
 - github：``https://github.com/tavisdxh/pytest-docs-zn``

-----


# 3. 测试中断言的编写和报告

## 3.1 使用assert语句断言

pytest允许使用标准的python assert来验证Python测试在的预期值。例如，可以这样写：

    # content of test_assert1.py
    def f():
        return 3

    def test_function():
        assert f() == 4

断言函数返回一个确定的值。如果断言失败，可以看到函数的返回值：

    $ pytest test_assert1.py
    ======= test session starts ========
    platform linux -- Python 3.5.2, pytest-3.0.7, py-1.4.32, pluggy-0.4.0
    rootdir: $REGENDOC_TMPDIR, inifile:
    collected 1 items

    test_assert1.py F

    ======= FAILURES ========
    _______ test_function ________

        def test_function():
    >       assert f() == 4
    E       assert 3 == 4
    E       + where 3 = f()

    test_assert1.py:5: AssertionError
    ======= 1 failed in 0.12 seconds ========

pytest支持显示最常见的子表达式的值，包括调用，属性，比较以及二进制和一元运算符。这允你使用没有样板代码的惯用的python结构，而不会失去内省信息。
因此，可以指定断言信息：

    assert a % 2 == 0, "值是奇数，应该是偶数"

那么就没有断言反省，信息会被简单地显示在回溯中。

## 3.2 断言预期异常

要写断言预期异常，可以使用``pytest.raises``作为上下文管理器：

import pytest

def test_zero_division():
    with pytest.raises(ZeroDivisionError):
        1 / 0

如果要访问实际异常信息，可以使用：

def test_recursion_depth():
    with pytest.raises(RuntimeError) as excinfo:
        def f():
            f()
        f()
    assert 'maximum recursion' in str(excinfo.value)

``excinfo``是一个ExceptionInfo的实例，它是围绕实际异常引发的装饰器。主要属性是`` .type``,``.value``,``.traceback``。

在上下文管理器形式，可以使用关键字参数消息来指定自定义失败消息：

    >>> with raises(ZeroDivisionError, message="Expecting ZeroDivisionError"):
    ... pass
    ... Failed: Expecting ZeroDivisionError

注意：也可以在``pytest.mark.xfail``指定"raises"参数，它会检查test抛出异常时是否抛出该异常：

    @pytest.mark.xfail(raises=IndexError)
    def test_f():
        f()

使用``pytest.raises``来测试代码里故意抛出异常可能会更好些，而使用带有check函数的``@pytest.mark.xfail``来记录未定义的错误（测试描述应该发生什么）或依赖关系的错误可能更好些。

如果要测试正则表达式与异常的字符串表示形式匹配（像Unittest的``TestCase.assertRaisesRegexp``方法），可以使用``assertRaisesRegexp``方法。

    import pytest

    def myfunc():
        raise ValueError("Exception 123 raised")

    def test_match():
        with pytest.raises(ValueError) as excinfo:
            myfunc()
        excinfo.match(r'.* 123 .*')

match方法的正则参数会被匹配到，它会使用到``re.search``功能。所以在上面的例子，``excinfo.match('123')``也起同样的作用。

## 3.3 断言指定警告

可以使用``pytest.warns``来检查代码引起指定的警告。

## 3.4 使用上下文相关的比较

pytest在遇到比较时提供上下文相关信息方面拥有丰富的支持。例如：

    # content of test_assert2.py

    def test_set_comparison():
        set1 = set("1308")
        set2 = set("8035")
        assert set1 == set2

执行模块：

    $ pytest test_assert2.py
    ======= test session starts ========
    platform linux -- Python 3.5.2, pytest-3.0.7, py-1.4.32, pluggy-0.4.0
    rootdir: $REGENDOC_TMPDIR, inifile:
    collected 1 items

    test_assert2.py F

    ======= FAILURES ========
    _______ test_set_comparison ________

        def test_set_comparison():
            set1 = set("1308")
            set2 = set("8035")
    >       assert set1 == set2
    E       AssertionError: assert {'0', '1', '3', '8'} == {'0', '3', '5', '8'}
    E           Extra items in the left set:
    E           '1'
    E           Extra items in the right set:
    E           '5'
    E           Use -v to get the full diff

    test_assert2.py:5: AssertionError
    ======= 1 failed in 0.12 seconds ========

## 3.5 自定义异常

可以通过实现``pytest_assertrepr_compare``钩子来添加自己的详细说明。

    pytest_assertrepr_compare(config, op, left, right)
        返回断言失败时的说明。

        返回None为无定义说明，否则返回字符串列表。字符串通过换行符拼接进入，但是字符串中的任何换行符都会被转义。注意，除了第一行之外，所有的一切都将略微缩进，意图是第一行是用来做总结的。

例如，考虑在conftest.py中添加以下钩子，它为Foo对象提供了一个替代解释：

    # content of conftest.py
    from test_foocompare import Foo
    def pytest_assertrepr_compare(op, left, right):
        if isinstance(left, Foo) and isinstance(right, Foo) and op == "==":
        return ['Comparing Foo instances:',' vals: %s != %s' % (left.val, right.val)]

测试文件：

    # content of test_foocompare.py
    class Foo:
        def __init__(self, val):
            self.val = val

        def __eq__(self, other):
            return self.val == other.val

        def test_compare():
            f1 = Foo(1)
            f2 = Foo(2)
            assert f1 == f2


执行：

    $ pytest -q test_foocompare.py
    F
    ======= FAILURES ========
    _______ test_compare ________

    def test_compare():
        f1 = Foo(1)
        f2 = Foo(2)
    >   assert f1 == f2
    E   assert Comparing Foo instances:
    E       vals: 1 != 2

    test_foocompare.py:11: AssertionError
    1 failed in 0.12 seconds

